// Goblin Studio — font-file resolver for the text overlay (v3, July 24 2026).
//
// HISTORY, so nobody re-lives it:
//   v1 downloaded .ttf files from Google Fonts using an ancient User-Agent.
//   On July 24 the production lambda's css2 responses stopped carrying .ttf
//   URLs at all — Google now serves format('woff') to that UA — so EVERY
//   family (including the Jost fallback) resolved to null and titles rendered
//   as an invisible 1×1 png. Root cause proven by /api/admin/font-debug.
//
// v3 PRINCIPLE — OWN THE FONTS: the app ships its own font pack and treats
// any network fetch as a last resort. Resolution order:
//   1. BUNDLED PACK (public/fonts + font-manifest.json, committed to the
//      repo, generated by `node scripts/fetch-fonts.mjs`) — read from disk.
//   2. BUNDLED PACK VIA OUR OWN CDN — if the lambda filesystem doesn't carry
//      public/ (Vercel tracing quirk), fetch the same file from our own
//      deployment's static hosting and cache it in /tmp.
//   3. GOOGLE FONTS RUNTIME DOWNLOAD — only for families not in the pack
//      (e.g. a custom font name typed by the user). Accepts BOTH truetype
//      and woff now (opentype.js parses woff1; never woff2).
// Every file from every layer is verified by actually parsing it with
// opentype.js and extracting a real 'A' outline before it is trusted.
// Callers fall back to the house font, then to the first bundled family —
// see text-overlay.ts — so titles can no longer silently vanish.

import { promises as fs } from "fs";
import path from "path";
import os from "os";
import manifestJson from "./font-manifest.json";

const CACHE_DIR = path.join(os.tmpdir(), "bg-font-cache");

// family → { "700": "file.woff", "700i": "file.woff", ... }
const MANIFEST: Record<string, Record<string, string>> = manifestJson as never;

export interface ResolvedFont {
  path: string;
  family: string;
  // Which layer produced the file — surfaced by /api/admin/font-debug.
  source: "bundled-fs" | "bundled-cdn" | "google" | "cache";
}

const memo = new Map<string, ResolvedFont | null>();

// An old User-Agent keeps the Google css2 response in single-file woff/ttf
// territory (modern UAs get woff2, which opentype.js cannot parse).
const TTF_UA = "Mozilla/5.0 (Windows NT 5.1; rv:7.0.1) Gecko/20100101 Firefox/7.0.1";

// The first family in the bundled pack — the overlay's renderer of last
// resort. With any pack committed at all, this is always available.
export const FIRST_BUNDLED_FAMILY: string | null = Object.keys(MANIFEST)[0] ?? null;

function safeName(family: string): string {
  return family.replace(/[^\w-]/g, "");
}

async function fileExists(p: string): Promise<boolean> {
  try { await fs.access(p); return true; } catch { return false; }
}

// ── Ground-truth verification: parse with opentype.js, probe a capital ──────
/* eslint-disable @typescript-eslint/no-explicit-any */
let opentypeMod: any | null = null;
async function opentype(): Promise<any> {
  if (!opentypeMod) {
    const m: any = await import("opentype.js");
    opentypeMod = typeof m?.parse === "function" ? m : m?.default;
  }
  return opentypeMod;
}

async function bufferIsUsableFont(buf: Buffer): Promise<boolean> {
  try {
    const ab = buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength);
    const font = (await opentype()).parse(ab);
    for (const ch of ["A", "R", "Z"]) {
      const d = font.getPath(ch, 0, 0, 64).toPathData(1);
      if (!d || d.length < 8) return false;
    }
    return true;
  } catch {
    return false;
  }
}

async function verifyFile(p: string, family: string, source: ResolvedFont["source"]): Promise<ResolvedFont | null> {
  try {
    const buf = await fs.readFile(p);
    if (!(await bufferIsUsableFont(buf))) return null;
    return { path: p, family, source };
  } catch {
    return null;
  }
}

// ── Layer 1+2: the bundled pack ─────────────────────────────────────────────

// Candidate filenames from the manifest, best match first: exact weight+style,
// then same style nearest weight, then any style nearest weight.
function manifestCandidates(family: string, weight: number, italic: boolean): string[] {
  const entry =
    MANIFEST[family] ??
    MANIFEST[Object.keys(MANIFEST).find((k) => k.toLowerCase() === family.toLowerCase()) ?? ""];
  if (!entry) return [];
  const parsed = Object.entries(entry).map(([key, file]) => ({
    w: parseInt(key, 10) || 400,
    i: key.endsWith("i"),
    file,
  }));
  const rank = (c: { w: number; i: boolean }): number =>
    Math.abs(c.w - weight) + (c.i === italic ? 0 : 1000);
  return parsed
    .sort((a, b) => rank(a) - rank(b))
    .map((c) => c.file)
    .filter((f, idx, arr) => arr.indexOf(f) === idx);
}

function siteBase(): string | null {
  const explicit = (process.env.NEXT_PUBLIC_SITE_URL ?? "").trim().replace(/\/+$/, "");
  if (explicit) return explicit;
  const vercel = (process.env.VERCEL_URL ?? "").trim();
  if (vercel) return `https://${vercel}`;
  return null;
}

async function tryBundled(family: string, weight: number, italic: boolean): Promise<ResolvedFont | null> {
  for (const file of manifestCandidates(family, weight, italic)) {
    // 1a. straight off the lambda/local filesystem
    const diskPath = path.join(process.cwd(), "public", "fonts", file);
    const fromDisk = await verifyFile(diskPath, family, "bundled-fs");
    if (fromDisk) return fromDisk;

    // 1b. previously fetched copy in /tmp
    const cached = path.join(CACHE_DIR, `bundled-${file}`);
    if (await fileExists(cached)) {
      const fromCache = await verifyFile(cached, family, "cache");
      if (fromCache) return fromCache;
      try { await fs.unlink(cached); } catch { /* ignore */ }
    }

    // 1c. our own deployment's static hosting (public/ is always served even
    // when it isn't on the lambda filesystem)
    const base = siteBase();
    if (base) {
      try {
        const res = await fetch(`${base}/fonts/${encodeURIComponent(file)}`);
        if (res.ok) {
          const buf = Buffer.from(await res.arrayBuffer());
          if (await bufferIsUsableFont(buf)) {
            await fs.mkdir(CACHE_DIR, { recursive: true });
            await fs.writeFile(cached, buf);
            return { path: cached, family, source: "bundled-cdn" };
          }
        }
      } catch { /* fall through */ }
    }
  }
  return null;
}

// ── Layer 3: Google Fonts runtime download (custom fonts only, last resort) ─

// Pick a parseable font URL from a css2 response. Prefer truetype/otf, accept
// woff (opentype.js parses woff1), NEVER woff2 (it cannot). Within a format,
// prefer the /* latin */ subset block when subset comments are present — a
// non-Latin subset has no A–Z glyphs at all (the original tofu bug).
export function pickFontUrlFromCss(css: string): string | null {
  const re =
    /\/\*\s*([\w-]+)\s*\*\/|url\((https:\/\/[^)\s'"]+)\)(?:\s*format\(\s*['"]?([\w-]+)['"]?\s*\))?/gi;
  let subset: string | null = null;
  const found: Array<{ url: string; ttf: boolean; latin: boolean }> = [];
  let m: RegExpExecArray | null;
  while ((m = re.exec(css)) !== null) {
    if (m[1]) { subset = m[1].toLowerCase(); continue; }
    const url = m[2];
    if (!url) continue;
    const fmt = (m[3] ?? "").toLowerCase();
    if (/\.woff2($|\?)/i.test(url) || fmt === "woff2") continue;
    const ttf = /\.(ttf|otf)($|\?)/i.test(url) || fmt === "truetype" || fmt === "opentype";
    const woff = /\.woff($|\?)/i.test(url) || fmt === "woff";
    if (!ttf && !woff) continue;
    found.push({ url, ttf, latin: subset === "latin" || subset === null });
  }
  const pickFrom = (list: typeof found): string | null =>
    (list.find((f) => f.latin) ?? list[list.length - 1])?.url ?? null;
  return pickFrom(found.filter((f) => f.ttf)) ?? pickFrom(found.filter((f) => !f.ttf));
}

// Back-compat alias (older imports).
export const pickTtfUrlFromCss = pickFontUrlFromCss;

async function tryGoogle(family: string, weight: number, italic: boolean): Promise<ResolvedFont | null> {
  const cacheFile = path.join(CACHE_DIR, `${safeName(family)}-${weight}${italic ? "i" : ""}.font`);
  if (await fileExists(cacheFile)) {
    const ok = await verifyFile(cacheFile, family, "cache");
    if (ok) return ok;
    try { await fs.unlink(cacheFile); } catch { /* ignore */ }
  }

  const famParam = family.replace(/ /g, "+");
  const candidates = italic
    ? [`:ital,wght@1,${weight}`, `:ital@1`, `:wght@${weight}`, ``]
    : [`:wght@${weight}`, ``];

  for (const axis of candidates) {
    try {
      const cssUrl = `https://fonts.googleapis.com/css2?family=${famParam}${axis}&display=swap`;
      const cssRes = await fetch(cssUrl, { headers: { "User-Agent": TTF_UA } });
      if (!cssRes.ok) continue;
      const fontUrl = pickFontUrlFromCss(await cssRes.text());
      if (!fontUrl) continue;

      const fontRes = await fetch(fontUrl);
      if (!fontRes.ok) continue;
      const buf = Buffer.from(await fontRes.arrayBuffer());
      if (!(await bufferIsUsableFont(buf))) continue;

      await fs.mkdir(CACHE_DIR, { recursive: true });
      await fs.writeFile(cacheFile, buf);
      return { path: cacheFile, family, source: "google" };
    } catch { /* try the next, looser request */ }
  }
  return null;
}

// ── Public API ──────────────────────────────────────────────────────────────

export async function getFontFile(
  family: string,
  weight = 700,
  italic = false
): Promise<ResolvedFont | null> {
  const fam = (family ?? "").trim();
  if (!fam) return null;
  const key = `${fam}:${weight}:${italic ? 1 : 0}`;
  if (memo.has(key)) return memo.get(key) ?? null;

  const resolved =
    (await tryBundled(fam, weight, italic)) ?? (await tryGoogle(fam, weight, italic));
  if (!resolved) {
    console.error(`[font-files] could not resolve "${fam}" (${weight}${italic ? "i" : ""}) from any layer`);
  }
  memo.set(key, resolved);
  return resolved;
}

// Back-compat wrapper (path only).
export async function getFontFilePath(
  family: string,
  weight = 700,
  italic = false
): Promise<string | null> {
  const r = await getFontFile(family, weight, italic);
  return r?.path ?? null;
}
